### ISSUE TITLE
Shinies break macro

### ISSUE THREAD

**Issue by Fad3ed0ng** [Cweamy/Fisch-Cream-s-Macro#2]
Every time a shiny fish bites the reel, the macro seems to not know how to catch the fish and fails the catch. Then the entire loop ends and doesn't continue until I stop the macro and start it again manually.

**Comment by Fad3ed0ng** [comment]
https://github.com/user-attachments/assets/c294304f-46d6-4c4b-9059-29c023559c3a

Using King's Rod with Blessed enchant.

**Comment by Cweamy** [comment]
maybe increase Tolerance on the grey bar code
