### ISSUE TITLE
"i reel 300" is 100% of the reason the macro is losing fish when I lose them.

### ISSUE THREAD

**Issue by youareeduc** [Cweamy/Fisch-Cream-s-Macro#3]
every now and then when a fish/bait crate or anything with a bar for the macro to catch, if it is close to the right side of the bar but now quite far enough for the bar to reach, "i reel 300" is shown at the cursor and stays there until I lose the fish, even when the fish moves to the left side of the bar.

**Comment by Cweamy** [comment]
i didn't code the part where it go left
