### ISSUE TITLE
idk what is this

### ISSUE THREAD

**Issue by khalid23kw** [Cweamy/Fisch-Cream-s-Macro#7]
![image](https://github.com/user-attachments/assets/e9857f14-3f7f-4f38-84e9-03e6913cf686)
    Error: This line does not contain a recognized action.

Text:	#SingleInstance, force
Line:	1
File:	C:\Users\USER\Downloads\Fisch-Cream-s-Macro-main\Fisch-Cream-s-Macro-main\Fisch Cream's Macro free edition.Ahk

The program will exit.

**Comment by Cweamy** [comment]
use ahk v1.1

**Comment by macrohelpME** [comment]
i downloaded that and it just closed what do i do
how do i macro, i used v2 and it just didnt reel in any fish
